PRODUCT_VERSION_MAJOR = 7
PRODUCT_VERSION_MINOR = 1
PRODUCT_VERSION_MAINTENANCE = 0

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=GWK74

#
# Set ro.modversion
#
PRODUCT_PROPERTY_OVERRIDES += \
  ro.modversion=TeamHeroC-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(shell date +%0d%^b%Y-%H%M%S)
